"""Changed is_free to boolean and changed name of pk in Extension to extension_id

Revision ID: cf51e5182f3e
Revises: dbc0140c6700
Create Date: 2023-12-21 13:53:39.015677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf51e5182f3e'
down_revision = 'dbc0140c6700'
branch_labels = None
depends_on = None

naming_convention = {
    "ix": 'ix_%(column_0_label)s',
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(column_0_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s"
}

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extension', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extension_id', sa.String(length=80), nullable=False))
        batch_op.create_unique_constraint('pk_extension', ['extension_id'])
        batch_op.drop_column('component_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_free',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Boolean(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_free',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    with op.batch_alter_table('extension', schema=None) as batch_op:
        batch_op.add_column(sa.Column('component_id', sa.VARCHAR(length=80), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('extension_id')

    # ### end Alembic commands ###
