"""empty message

Revision ID: 096a2fbd3610
Revises: 3a45877310c7
Create Date: 2024-01-07 12:56:08.727117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '096a2fbd3610'
down_revision = '3a45877310c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extension', schema=None) as batch_op:
        batch_op.add_column(sa.Column('handle_border_color', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extension', schema=None) as batch_op:
        batch_op.drop_column('handle_border_color')

    # ### end Alembic commands ###
