"""Adding alt_text columns to the ComponentSlider table.

Revision ID: 328e8454af44
Revises: ca03c66e8363
Create Date: 2023-08-17 05:44:34.839368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '328e8454af44'
down_revision = 'ca03c66e8363'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('component_slider', schema=None) as batch_op:
        batch_op.add_column(sa.Column('before_alt_text', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('after_alt_text', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('component_slider', schema=None) as batch_op:
        batch_op.drop_column('after_alt_text')
        batch_op.drop_column('before_alt_text')

    # ### end Alembic commands ###
