"""Drop user_id column from User table.

Revision ID: 38f0548da6df
Revises: bb4dd6a94001
Create Date: 2023-12-21 13:40:46.243562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38f0548da6df'
down_revision = 'bb4dd6a94001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.VARCHAR(length=200), nullable=True))

    # ### end Alembic commands ###
