"""empty message

Revision ID: 3a45877310c7
Revises: 
Create Date: 2024-01-05 14:25:26.021462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a45877310c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extension', schema=None) as batch_op:
        batch_op.add_column(sa.Column('before_image_thumbnail', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('after_image_thumbnail', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extension', schema=None) as batch_op:
        batch_op.drop_column('after_image_thumbnail')
        batch_op.drop_column('before_image_thumbnail')

    # ### end Alembic commands ###
