"""empty message

Revision ID: 3b3ac9101ff3
Revises: edb5e6b092cb
Create Date: 2024-01-18 02:06:42.315988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b3ac9101ff3'
down_revision = 'edb5e6b092cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extension', schema=None) as batch_op:
        batch_op.alter_column('before_label_text',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=30),
               existing_nullable=True)
        batch_op.alter_column('before_alt_text',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=60),
               existing_nullable=True)
        batch_op.alter_column('after_label_text',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=30),
               existing_nullable=True)
        batch_op.alter_column('after_alt_text',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=60),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extension', schema=None) as batch_op:
        batch_op.alter_column('after_alt_text',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
        batch_op.alter_column('after_label_text',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
        batch_op.alter_column('before_alt_text',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
        batch_op.alter_column('before_label_text',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)

    # ### end Alembic commands ###
