"""empty message

Revision ID: 4c41f3fcb0cd
Revises: d6bfc695e479
Create Date: 2024-01-25 13:05:17.631010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c41f3fcb0cd'
down_revision = 'd6bfc695e479'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extension_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('extension_limit', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instance', schema=None) as batch_op:
        batch_op.drop_column('extension_limit')
        batch_op.drop_column('extension_count')

    # ### end Alembic commands ###
