"""Inital migration to Postgres db 12-26-2023

Revision ID: 563177877571
Revises: 
Create Date: 2023-12-26 22:28:30.234991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '563177877571'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('instance_id', sa.String(length=200), nullable=False),
    sa.Column('site_id', sa.String(length=200), nullable=True),
    sa.Column('refresh_token', sa.String(length=200), nullable=True),
    sa.Column('is_free', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('instance_id'),
    sa.UniqueConstraint('instance_id'),
    sa.UniqueConstraint('site_id')
    )
    op.create_table('extension',
    sa.Column('extension_id', sa.String(length=80), nullable=False),
    sa.Column('instance_id', sa.String(length=80), nullable=True),
    sa.Column('before_image', sa.String(length=1000), nullable=True),
    sa.Column('before_label_text', sa.String(length=1000), nullable=True),
    sa.Column('before_alt_text', sa.String(length=1000), nullable=True),
    sa.Column('after_image', sa.String(length=1000), nullable=True),
    sa.Column('after_label_text', sa.String(length=1000), nullable=True),
    sa.Column('after_alt_text', sa.String(length=1000), nullable=True),
    sa.Column('offset', sa.Integer(), nullable=True),
    sa.Column('offset_float', sa.Float(), nullable=True),
    sa.Column('is_vertical', sa.Boolean(), nullable=True),
    sa.Column('mouseover_action', sa.Integer(), nullable=True),
    sa.Column('handle_animation', sa.Integer(), nullable=True),
    sa.Column('is_move_on_click_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['user.instance_id'], ),
    sa.PrimaryKeyConstraint('extension_id'),
    sa.UniqueConstraint('extension_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('extension')
    op.drop_table('user')
    # ### end Alembic commands ###
