"""Added label_text columns to the ComponentSlider table.

Revision ID: 58506234d183
Revises: 328e8454af44
Create Date: 2023-11-24 12:15:00.756111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58506234d183'
down_revision = '328e8454af44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('component_slider', schema=None) as batch_op:
        batch_op.add_column(sa.Column('before_label_text', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('after_label_text', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('component_slider', schema=None) as batch_op:
        batch_op.drop_column('after_label_text')
        batch_op.drop_column('before_label_text')

    # ### end Alembic commands ###
