"""empty message

Revision ID: 689915235526
Revises: 4c41f3fcb0cd
Create Date: 2024-01-26 14:45:10.203777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '689915235526'
down_revision = '4c41f3fcb0cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_url', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instance', schema=None) as batch_op:
        batch_op.drop_column('site_url')

    # ### end Alembic commands ###
