"""Attempting another migration.

Revision ID: bb4dd6a94001
Revises: b88cef0c8da6
Create Date: 2023-12-21 13:38:55.453594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb4dd6a94001'
down_revision = 'b88cef0c8da6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_component_slider')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_component_slider',
    sa.Column('instance_id', sa.VARCHAR(length=200), nullable=True),
    sa.Column('extension_id', sa.VARCHAR(length=200), nullable=False),
    sa.Column('is_vertical', sa.BOOLEAN(), nullable=True),
    sa.Column('mouseover_action', sa.INTEGER(), nullable=True),
    sa.Column('handle_animation', sa.INTEGER(), nullable=True),
    sa.Column('is_move_on_click_enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('last_modified', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('before_image', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('after_image', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('offset', sa.INTEGER(), nullable=True),
    sa.Column('offset_float', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('before_alt_text', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('after_alt_text', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('before_label_text', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('after_label_text', sa.VARCHAR(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['user.instance_id'], name='fk_component_slider_instance_id_user'),
    sa.UniqueConstraint('extension_id', name='fk_instance_id')
    )
    # ### end Alembic commands ###
