"""Rename ComponentSlider table as Extension table.

Revision ID: dbc0140c6700
Revises: efdfdd2c106e
Create Date: 2023-12-21 13:47:02.822541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbc0140c6700'
down_revision = 'efdfdd2c106e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('component_slider')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('component_slider',
    sa.Column('component_id', sa.VARCHAR(length=80), nullable=False),
    sa.Column('instance_id', sa.VARCHAR(length=80), nullable=True),
    sa.Column('before_image', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('after_image', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('offset', sa.INTEGER(), nullable=True),
    sa.Column('offset_float', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('before_alt_text', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('after_alt_text', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('before_label_text', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('after_label_text', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('is_vertical', sa.BOOLEAN(), nullable=True),
    sa.Column('mouseover_action', sa.INTEGER(), nullable=True),
    sa.Column('handle_animation', sa.INTEGER(), nullable=True),
    sa.Column('is_move_on_click_enabled', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['user.instance_id'], ),
    sa.PrimaryKeyConstraint('component_id'),
    sa.UniqueConstraint('component_id')
    )
    # ### end Alembic commands ###
