"""Drop orientation column.

Revision ID: de1b0cb5e87c
Revises: 38f0548da6df
Create Date: 2023-12-21 13:42:01.908992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de1b0cb5e87c'
down_revision = '38f0548da6df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('component_slider', schema=None) as batch_op:
        batch_op.drop_column('orientation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('component_slider', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orientation', sa.VARCHAR(length=1000), nullable=True))

    # ### end Alembic commands ###
