"""empty message

Revision ID: edb5e6b092cb
Revises: 096a2fbd3610
Create Date: 2024-01-17 01:53:01.082655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edb5e6b092cb'
down_revision = '096a2fbd3610'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extension', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_dark', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extension', schema=None) as batch_op:
        batch_op.drop_column('is_dark')

    # ### end Alembic commands ###
